# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#save-and-restore-gradle-dependency-cache

agents:
  queue: "android"

steps:
  - label: "Publish catalog"
    key: "publish"
    plugins: *common_plugins
    command: |
      .buildkite/publish.sh

  - label: "Cache dependencies"
    depends_on:
      - "publish"
    if: build.tag != null
    plugins: *common_plugins
    command: |
      .buildkite/cache.sh
