common-params:
  &docker-container
  docker#v3.8.0:
    image: "public.ecr.aws/automattic/android-build-image:v1.2.0"

steps:
  - label: "Publish catalog"
    if: build.tag != null
    plugins:
      - *docker-container
    command:
      ./gradlew -p catalog prepareToPublishToS3 --tag-name=$BUILDKITE_TAG publishMavenPublicationToS3Repository

  - label: "Cache dependencies"
    if: build.tag != null
    plugins:
      - *docker-container
      - automattic/bash-cache
    command: |
      ./gradlew -p cache-generator/ -P catalogVersion=$BUILDKITE_TAG build

      # https://docs.gradle.org/current/userguide/dependency_resolution.html#sub:cache_copy
      mkdir gradle-modules-cache \
          && cp -r $HOME/.gradle/caches/modules-2 ./gradle-modules-cache \
          && find gradle-modules-cache/ -name "*.lock" -or -name "gc.properties" | xargs rm -r

      save_cache gradle-modules-cache "GRADLE-DEPENDENCIES-FOR-CATALOG-$BUILDKITE_TAG"
